"""NCIE WBS-15 local foundation service."""

from .app import FoundationApp, app
from .composition import ComposedFoundationService, compose_foundation_service
from .harness import InProcessHarness, InProcessResponse
from .lifecycle import LifecycleComponent, LifecycleState, ServiceLifecycle
from .observability import (
    FoundationObservabilityHooks,
    InMemoryObservabilitySink,
    MetricObservation,
    OperationalEvent,
    SignalCategory,
    TraceSpan,
)
from .readiness import ReadinessRegistry, ReadinessSnapshot
from .request_context import IdentityContext, IdentityState, RequestContext
from .routing import ApplicationResponse, RouteDefinition, RouteRegistry
from .security_authorization import (
    AuthorizationDimension,
    AuthorizationEffect,
    CurrentAuthorizationDecision,
    CurrentAuthorizationRequest,
    DenyAllPolicyDecisionPoint,
    PolicyDecisionPoint,
    PolicyEnforcementPoint,
    SecurityDecisionSignals,
    WBS15AuthorizationAdapter,
)
from .security_governance import (
    APPROVED_DEVELOPMENT_RISK_APPETITE,
    APPROVED_THREAT_ASSUMPTIONS,
    SECURITY_GOVERNANCE_BASELINE_VERSION,
    SECURITY_GOVERNANCE_DECISION_EVIDENCE,
    AuthorityAssignment,
    AuthorityRegistry,
    DevelopmentRiskEvaluator,
    DevelopmentRiskRequest,
    GovernanceDecision,
    GovernanceDecisionRecord,
    GovernanceDecisionValidator,
    GovernanceValidationCode,
    GovernedAct,
    GovernedTarget,
    InstitutionalRole,
    ReviewRecommendation,
    RiskAppetiteLevel,
    RiskDomain,
    RiskEvaluationDisposition,
    RiskTreatment,
    RiskTreatmentPlan,
    SecurityArchitectureReview,
    SecurityControlOwnership,
    ThreatAssumption,
)
from .security_principals import (
    AuthoritativeSourceCategory,
    IdentitySourceBoundary,
    PrincipalClass,
    SecurityPrincipal,
    UnboundIdentitySource,
    authoritative_source_for,
)

__all__ = [
    "APPROVED_DEVELOPMENT_RISK_APPETITE",
    "APPROVED_THREAT_ASSUMPTIONS",
    "SECURITY_GOVERNANCE_BASELINE_VERSION",
    "SECURITY_GOVERNANCE_DECISION_EVIDENCE",
    "ApplicationResponse",
    "AuthoritativeSourceCategory",
    "AuthorityAssignment",
    "AuthorityRegistry",
    "AuthorizationDimension",
    "AuthorizationEffect",
    "ComposedFoundationService",
    "CurrentAuthorizationDecision",
    "CurrentAuthorizationRequest",
    "DenyAllPolicyDecisionPoint",
    "DevelopmentRiskEvaluator",
    "DevelopmentRiskRequest",
    "FoundationApp",
    "FoundationObservabilityHooks",
    "GovernanceDecision",
    "GovernanceDecisionRecord",
    "GovernanceDecisionValidator",
    "GovernanceValidationCode",
    "GovernedAct",
    "GovernedTarget",
    "IdentityContext",
    "IdentitySourceBoundary",
    "IdentityState",
    "InMemoryObservabilitySink",
    "InProcessHarness",
    "InProcessResponse",
    "InstitutionalRole",
    "LifecycleComponent",
    "LifecycleState",
    "MetricObservation",
    "OperationalEvent",
    "PolicyDecisionPoint",
    "PolicyEnforcementPoint",
    "PrincipalClass",
    "ReadinessRegistry",
    "ReadinessSnapshot",
    "RequestContext",
    "ReviewRecommendation",
    "RiskAppetiteLevel",
    "RiskDomain",
    "RiskEvaluationDisposition",
    "RiskTreatment",
    "RiskTreatmentPlan",
    "RouteDefinition",
    "RouteRegistry",
    "SecurityArchitectureReview",
    "SecurityControlOwnership",
    "SecurityDecisionSignals",
    "SecurityPrincipal",
    "ServiceLifecycle",
    "SignalCategory",
    "ThreatAssumption",
    "TraceSpan",
    "UnboundIdentitySource",
    "WBS15AuthorizationAdapter",
    "app",
    "authoritative_source_for",
    "compose_foundation_service",
]
