"""NCIE-003 Chapter 42 master open-decision register.

Complete, exhaustive register of every Human Review Focus item raised in
Chapters 1-41 (123 items), added in the v0.3 hardening pass after the first
human review of v0.2 identified that Chapter 42 previously held only a
representative subset. Each entry carries the full governance column set
requested by that review: Decision ID, Issue, Originating Chapter, Category,
Impact, Blocking/Non-Blocking, Proposed Default (if any), Owner, Required
Evidence, Status, Decision, Effective Date.
"""

REGISTER = [
    dict(id="1-A", chapter=1, issue="Confirm the approval authority for NCIE-003 as a whole and for individual chapter sign-off.",
         category="INSTITUTIONAL", impact="Without a named authority, no chapter can formally leave IN DEVELOPMENT status.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function / NCA Executive Sponsor",
         evidence="Recorded appointment of NCIE-003 approval authority.", status="Open", decision="—", effective="—"),
    dict(id="1-B", chapter=1, issue="Confirm whether any existing NCA enterprise data-governance standard already exists and must be adopted rather than superseded by this chapter's change-control model.",
         category="SOURCE_DISCOVERY", impact="An undiscovered existing standard could conflict with Chapter 1's change-control process once real NCA teams start using it.",
         blocking="Non-blocking (governance refinement)", proposed=None, owner="NCIE Architecture Function",
         evidence="NCA enterprise data-governance policy document, if one exists.", status="Open", decision="—", effective="—"),
    dict(id="1-C", chapter=1, issue="When a skeletal definition becomes an authoritative baseline.",
         category="RESOLVED", impact="N/A — already settled.", blocking="Non-blocking",
         proposed=None, owner="N/A", evidence="N/A — resolved by front matter §0.2/§0.3.",
         status="Closed", decision="Skeletal-structure approval authorizes expansion; each chapter separately requires explicit approval before its content is binding.",
         effective="NCIE-003 v0.2 front matter"),

    dict(id="2-A", chapter=2, issue="Approve the enterprise naming conventions in §2.4 as binding across all NCIE domains, including any existing NCA-wide systems this may eventually touch.",
         category="INSTITUTIONAL", impact="Unapproved conventions risk inconsistent field naming once NCIE-004 implementation begins.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Recorded approval of §2.4 as binding.", status="Open", decision="—", effective="—"),
    dict(id="2-B", chapter=2, issue="The null/unknown state vocabulary in §2.5 is proposed as the binding standard for all 43 chapters.",
         category="PROPOSED", impact="If overridden late, every domain chapter's Unknown/Partial/Stale/Unavailable modelling would need revisiting.",
         blocking="Non-blocking (default stands until overridden)", proposed="Bind §2.5 as-is; technically defensible from NCIE-002 alone.",
         owner="NCIE Architecture Function", evidence="NCA confirmation or override of the proposed vocabulary.", status="Open — proposed default standing", decision="—", effective="—"),
    dict(id="2-C", chapter=2, issue="Confirm whether NCA already operates an enterprise data-modelling standard (naming, null-handling or otherwise) that NCIE-003 must adopt rather than establish independently.",
         category="SOURCE_DISCOVERY", impact="Same risk as 1-B, specific to modelling standards rather than governance process.",
         blocking="Non-blocking (governance refinement)", proposed=None, owner="NCIE Architecture Function",
         evidence="NCA data-modelling standard document, if one exists.", status="Open", decision="—", effective="—"),

    dict(id="3-A", chapter=3, issue="Confirm the principal enterprise entities in §3.3 against NCA's actual organisational view of its own data assets.",
         category="INSTITUTIONAL", impact="A missing enterprise entity family would require rework across every domain chapter that should reference it.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="NCA sign-off on the enterprise entity catalogue.", status="Open", decision="—", effective="—"),
    dict(id="3-B", chapter=3, issue="Identify any NCA-wide master entity not yet represented (e.g. an existing enterprise operator master list) that should be adopted as the canonical source rather than re-created.",
         category="SOURCE_DISCOVERY", impact="Re-creating a master list NCA already maintains would create a second, potentially conflicting source of truth.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="Inventory of existing NCA master-data assets.", status="Open", decision="—", effective="—"),
    dict(id="3-C", chapter=3, issue="(v0.4) Confirm canonical stewardship/ownership for the new Agent & VPF entity family (§3.9), consistent with the existing per-family ownership model in §3.6.",
         category="INSTITUTIONAL", impact="Unclear stewardship risks the Agent & VPF family lacking an accountable steward once NCIE-004/005/006 begin implementation.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved stewardship assignment for the Agent & VPF entity family.", status="Open", decision="—", effective="—"),

    dict(id="4-A", chapter=4, issue="Confirm identifier formats where institutionally constrained (e.g. any existing NCA-mandated operator or facility identifier scheme).",
         category="INSTITUTIONAL", impact="A conflicting mandated ID format would require adapting Ch.4's Canonical ID / External ID split.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="NCA-mandated identifier scheme documentation, if any.", status="Open", decision="—", effective="—"),
    dict(id="4-B", chapter=4, issue="Confirm authoritative master-data sources for core entities (Operator, Geography).",
         category="SOURCE_DISCOVERY", impact="Determines whether NCIE-003 seeds its own master list or synchronises against an existing one.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="Confirmed existing NCA master-data source, or confirmation none exists.", status="Open", decision="—", effective="—"),
    dict(id="4-C", chapter=4, issue="The ambiguous-match handling in §4.4 (never force-resolve automatically) is proposed as the binding default for all identity resolution across NCIE-003.",
         category="PROPOSED", impact="If overridden, downstream chapters relying on this rule (Ch.14, Ch.34) would need re-review.",
         blocking="Non-blocking (default stands until overridden)", proposed="Never force-resolve an ambiguous match automatically.",
         owner="NCIE Architecture Function", evidence="NCA confirmation or override.", status="Open — proposed default standing", decision="—", effective="—"),

    dict(id="5-A", chapter=5, issue="UTC as the canonical storage time zone with Ghana local time derived for display.",
         category="PROPOSED", impact="A different storage time zone choice would ripple through every timestamped entity in the document.",
         blocking="Non-blocking (default stands until overridden)", proposed="UTC storage, GMT display.",
         owner="NCIE Architecture Function", evidence="NCA confirmation or override.", status="Open — proposed default standing", decision="—", effective="—"),
    dict(id="5-B", chapter=5, issue="Confirm which entities beyond the §5.5 list require full bitemporal storage versus knowledge-time-only.",
         category="INSTITUTIONAL", impact="Under-scoping bitemporal coverage risks losing decision-time defensibility for a data class that needed it.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function",
         evidence="Reviewed and confirmed §5.5 entity list.", status="Open", decision="—", effective="—"),
    dict(id="5-C", chapter=5, issue="Confirm legal/operational expectations for how far back historical reconstruction must be defensible.",
         category="LEGAL", impact="Determines Ch.31 retention and Ch.35 archival tiering; under-retention could break a future regulatory reconstruction.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Compliance",
         evidence="NCA legal/records-retention policy.", status="Open", decision="—", effective="—"),

    dict(id="6-A", chapter=6, issue="Inventory actual NCA/operator source systems, their current owners and provider channels.",
         category="SOURCE_DISCOVERY", impact="Without this, the Source Registry entities remain structurally ready but empty — nothing can actually ingest.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function / NCA Source Owners",
         evidence="Completed source inventory.", status="Open", decision="—", effective="—"),
    dict(id="6-B", chapter=6, issue="Confirm source ownership and trust hierarchy where more than one plausible owner exists.",
         category="INSTITUTIONAL", impact="Unclear ownership risks disputed data-quality accountability once a source misbehaves.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Resolved ownership assignment for jointly-relevant sources.", status="Open", decision="—", effective="—"),
    dict(id="6-C", chapter=6, issue="Confirm which sources arrive via API, file, stream, RPA or manual upload today.",
         category="SOURCE_DISCOVERY", impact="Determines which Provider adapters (Ch.21 of NCIE-002) must actually be built first.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function / NCA Source Owners",
         evidence="Confirmed provider-channel inventory per source.", status="Open", decision="—", effective="—"),

    dict(id="7-A", chapter=7, issue="Confirm available network source fields per operator NMS/PM export format.",
         category="SOURCE_DISCOVERY", impact="Blocks populating PM Observation's Source-System Field Mapping.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering",
         evidence="Sample operator NMS/PM export inspected.", status="Open", decision="—", effective="—"),
    dict(id="7-B", chapter=7, issue="Confirm the authoritative KPI set, formulas and units.",
         category="INSTITUTIONAL", impact="Without a confirmed KPI set, Ch.7 thresholds and Ch.18 REWS alerting cannot use real values.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering",
         evidence="Approved KPI definition set loaded into the Ch.24 Rule Service.", status="Open", decision="—", effective="—"),
    dict(id="7-C", chapter=7, issue="Confirm cell/site master-data authority and update process.",
         category="SOURCE_DISCOVERY", impact="Determines whether Ch.7/Ch.8 seed their own cell master or synchronise with an existing NCA/operator one.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering",
         evidence="Confirmed cell/site master-data source.", status="Open", decision="—", effective="—"),

    dict(id="8-A", chapter=8, issue="Confirm authoritative GIS datasets (region/district boundaries, site coordinates) currently available at NCA/operators.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Ch.8 geometry entities with real data.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering / GIS",
         evidence="Confirmed GIS dataset sources.", status="Open", decision="—", effective="—"),
    dict(id="8-B", chapter=8, issue="Confirm coordinate system and precision standards to be used as the canonical storage CRS.",
         category="INSTITUTIONAL", impact="A later CRS change would require re-projecting every stored geometry.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering / GIS",
         evidence="Approved canonical CRS.", status="Open", decision="—", effective="—"),
    dict(id="8-C", chapter=8, issue="Confirm which users/roles may see sensitive location layers.",
         category="INSTITUTIONAL", impact="Under-scoping this risks either over-exposing Anti-Fraud location data or blocking legitimate Network use.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA IT Security / Anti-Fraud",
         evidence="Approved role-to-layer permission mapping (cross-references NCIE-002 Ch.4).", status="Open", decision="—", effective="—"),

    dict(id="9-A", chapter=9, issue="Confirm existing drive-test systems, vendors and export formats.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Ch.9 Campaign/Measurement Source-System Field Mapping.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Engineering (Drive-Test)",
         evidence="Confirmed drive-test vendor/export inventory.", status="Open", decision="—", effective="—"),
    dict(id="9-B", chapter=9, issue="Confirm mandatory campaign metadata for a campaign to be treated as evidential.",
         category="INSTITUTIONAL", impact="Without this, Campaign Status's evidential-status attribute cannot be populated meaningfully.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Network Engineering (Drive-Test)",
         evidence="Approved mandatory-metadata list.", status="Open", decision="—", effective="—"),
    dict(id="9-C", chapter=9, issue="Confirm retention and evidential status of drive-test outputs for regulatory purposes.",
         category="LEGAL", impact="Under-retention could remove evidence needed for a future QoS enforcement action.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Compliance",
         evidence="NCA policy on drive-test evidential status.", status="Open", decision="—", effective="—"),

    dict(id="10-A", chapter=10, issue="Confirm incident reporting workflow and mailbox structure currently used by operators.",
         category="SOURCE_DISCOVERY", impact="Blocks configuring the Mailbox Connector/Extractor with real mailbox targets and field patterns.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Operations",
         evidence="Confirmed operator incident-mailbox inventory.", status="Open", decision="—", effective="—"),
    dict(id="10-B", chapter=10, issue="Confirm operator incident email fields available for extraction.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Incident Report's Source-System Field Mapping.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Operations",
         evidence="Sample operator incident emails inspected.", status="Open", decision="—", effective="—"),
    dict(id="10-C", chapter=10, issue="Confirm what constitutes validated restoration for closure purposes.",
         category="INSTITUTIONAL", impact="Without this, Incident Status cannot distinguish restoration-claimed from restoration-verified in practice.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Operations",
         evidence="Approved restoration-verification criteria.", status="Open", decision="—", effective="—"),

    dict(id="11-A", chapter=11, issue="Confirm source granularity and frequency of traffic reporting per operator.",
         category="SOURCE_DISCOVERY", impact="Blocks Traffic Observation's period/coverage attributes and, transitively, Revenue Calculation timing.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Revenue Assurance",
         evidence="Confirmed per-operator reporting granularity/frequency.", status="Open", decision="—", effective="—"),
    dict(id="11-B", chapter=11, issue="Confirm units and direction conventions to standardise across operators.",
         category="INSTITUTIONAL", impact="Inconsistent units across operators would corrupt cross-operator Traffic comparisons and Revenue calculations.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Revenue Assurance",
         evidence="Approved standard units/direction convention.", status="Open", decision="—", effective="—"),
    dict(id="11-C", chapter=11, issue="Revisions are proposed to always be modelled as new versions with a Correction relationship, never in-place overwrites.",
         category="PROPOSED", impact="If overridden, Ch.12's Revenue reproducibility guarantee would weaken.",
         blocking="Non-blocking (default stands until overridden)", proposed="Always version Traffic revisions via Correction relationship.",
         owner="NCIE Architecture Function", evidence="NCA confirmation or override.", status="Open — proposed default standing", decision="—", effective="—"),

    dict(id="12-A", chapter=12, issue="Confirm the exact surcharge formula, legal basis and charging basis (per-minute, per-call, or other).",
         category="LEGAL", impact="Without this, Revenue Calculation cannot produce a legally defensible figure, only a structurally correct placeholder.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Revenue Assurance",
         evidence="Confirmed legal basis and formula documented and loaded as a Ch.24 Rule.", status="Open", decision="—", effective="—"),
    dict(id="12-B", chapter=12, issue="Confirm who may change the surcharge rate and who approves a rate change.",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.24's Rule approval workflow for this specific rule key.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Revenue Assurance",
         evidence="Approved rate-change authority and process.", status="Open", decision="—", effective="—"),
    dict(id="12-C", chapter=12, issue="Confirm billing-verification source system and the reconciliation workflow currently used, if any.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Billing Verification's Source-System Field Mapping and Reconciliation workflow integration.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Revenue Assurance",
         evidence="Confirmed billing-verification source and existing workflow, if any.", status="Open", decision="—", effective="—"),

    dict(id="13-A", chapter=13, issue="Confirm source system, currency and daily cut-off time for Mobile Money aggregate reporting.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Mobile Money Aggregate's Source-System Field Mapping.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Mobile Money Oversight",
         evidence="Confirmed source system, currency and cut-off time.", status="Open", decision="—", effective="—"),
    dict(id="13-B", chapter=13, issue="Confirm whether any additional approved aggregate measures (e.g. transaction counts) should be added.",
         category="INSTITUTIONAL", impact="A missing approved measure would require a schema addition after go-live.",
         blocking="Non-blocking (additive change is low-cost, per Ch.2 §2.8)", proposed=None, owner="NCA Mobile Money Oversight",
         evidence="Confirmed final aggregate-measure list.", status="Open", decision="—", effective="—"),

    dict(id="14-A", chapter=14, issue="The current supplied limits of 10 (Ghana Card) and 3 (Passport) are proposed as the initial Ch.24 Rule Service values.",
         category="PROPOSED", impact="If overridden, only the Ch.24 Rule Version values change — no schema change needed, by design.",
         blocking="Non-blocking (default stands until overridden)", proposed="Ghana Card limit 10, Passport limit 3 as initial Rule Version values.",
         owner="NCA Registration & Identity Policy", evidence="NCA confirmation or override.", status="Open — proposed default standing", decision="—", effective="—"),
    dict(id="14-B", chapter=14, issue="Confirm the exact lifecycle states counted toward the limit (e.g. does a ported-out SIM still count?).",
         category="INSTITUTIONAL", impact="Wrong Countable State logic could wrongly trigger or suppress Registration Exceptions at scale.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Registration & Identity Policy",
         evidence="Approved Countable State rule set.", status="Open", decision="—", effective="—"),
    dict(id="14-C", chapter=14, issue="Confirm field-level protection scope for Protected Identity Reference — which roles may view unmasked values, and under what legal authority.",
         category="LEGAL", impact="Under-protection risks unlawful exposure of Ghana Card/Passport data; over-protection blocks legitimate registration review.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Data Protection",
         evidence="NCA legal authority and approved role scope.", status="Open", decision="—", effective="—"),

    dict(id="15-A", chapter=15, issue="Confirm actual Anti-Fraud workflow, tools and detection sources currently used at NCA.",
         category="SOURCE_DISCOVERY", impact="Blocks aligning SIMBOX Detection/Investigation entities with the real operational workflow.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Anti-Fraud Unit",
         evidence="Confirmed Anti-Fraud workflow and tool inventory.", status="Open", decision="—", effective="—"),
    dict(id="15-B", chapter=15, issue="Confirm what location data is received and at what precision.",
         category="SOURCE_DISCOVERY", impact="Blocks populating Location Evidence's Source Mapping and setting realistic Ch.8 spatial-precision expectations.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Anti-Fraud Unit",
         evidence="Confirmed location-data source and precision.", status="Open", decision="—", effective="—"),
    dict(id="15-C", chapter=15, issue="Confirm blocking interfaces, approval matrix and verification process with operators.",
         category="INSTITUTIONAL", impact="Blocks finalising Blocking Request/Action/Verification's provider integration and approval gates.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Anti-Fraud Unit",
         evidence="Approved blocking-interface and approval-matrix documentation.", status="Open", decision="—", effective="—"),

    dict(id="16-A", chapter=16, issue="Confirm NCA case/finding terminology and existing Regulatory Intelligence platform's own object model.",
         category="SOURCE_DISCOVERY", impact="Misaligned terminology risks NCIE-003 duplicating fields the existing platform already owns under different names.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Regulatory Intelligence",
         evidence="Existing platform's data model/terminology documented.", status="Open", decision="—", effective="—"),
    dict(id="16-B", chapter=16, issue="Confirm decision authorities and approval levels per case category.",
         category="INSTITUTIONAL", impact="Blocks finalising Decision Authority's role scoping in Ch.26.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Regulatory Intelligence",
         evidence="Approved decision-authority matrix.", status="Open", decision="—", effective="—"),
    dict(id="16-C", chapter=16, issue="Confirm which decisions require preserved Rationale and Decision-Time Snapshot as a matter of regulatory defensibility.",
         category="LEGAL", impact="Under-scoping risks a future Decision lacking the reconstruction evidence needed to defend it.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Regulatory Intelligence",
         evidence="NCA legal guidance on required decision evidence.", status="Open", decision="—", effective="—"),

    dict(id="17-A", chapter=17, issue="Confirm what NCA recognizes as formal Evidence for regulatory/legal purposes.",
         category="LEGAL", impact="Misalignment risks Evidence Objects that do not actually satisfy NCA's own evidentiary standard.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Compliance",
         evidence="NCA legal definition of admissible/formal Evidence.", status="Open", decision="—", effective="—"),
    dict(id="17-B", chapter=17, issue="Confirm chain-of-custody requirements in detail (algorithm, re-verification frequency).",
         category="LEGAL", impact="An unspecified or weak hashing/re-verification regime weakens Evidence's defensibility in a formal proceeding.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / IT Security",
         evidence="Approved chain-of-custody standard.", status="Open", decision="—", effective="—"),
    dict(id="17-C", chapter=17, issue="Confirm retention and correction rules for Evidence.",
         category="INSTITUTIONAL", impact="Feeds Ch.31's retention schedule; an unresolved rule here blocks Ch.31 finalisation.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Compliance",
         evidence="Approved Evidence retention/correction policy.", status="Open", decision="—", effective="—"),

    dict(id="18-A", chapter=18, issue="Confirm REWS severity taxonomy and escalation timing per category.",
         category="INSTITUTIONAL", impact="Blocks loading real Alert Rule severity/escalation values into Ch.24's Rule Service.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA Network Operations / REWS",
         evidence="Approved severity taxonomy and escalation timing.", status="Open", decision="—", effective="—"),
    dict(id="18-B", chapter=18, issue="Confirm Alert acknowledgement/escalation workflow and closure authority.",
         category="INSTITUTIONAL", impact="Blocks finalising who may acknowledge, escalate and close an Alert.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Network Operations / REWS",
         evidence="Approved workflow and closure-authority documentation.", status="Open", decision="—", effective="—"),
    dict(id="18-C", chapter=18, issue="Confirm which domains are mandatory for a complete National Operating Picture at launch.",
         category="INSTITUTIONAL", impact="Under-scoping risks launching an NOP that looks complete but omits a domain NCA considers essential.",
         blocking="Non-blocking (can proceed provisionally, expand post-launch)", proposed=None, owner="NCA Network Operations",
         evidence="Approved launch-scope domain list.", status="Open", decision="—", effective="—"),

    dict(id="19-A", chapter=19, issue="Confirm which relationship types are operationally useful for launch.",
         category="INSTITUTIONAL", impact="Under-scoping risks a Fusion graph too sparse to support the priority use cases NCA actually needs at launch.",
         blocking="Non-blocking (additive change is low-cost, per Ch.2 §2.8)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved launch relationship-type list.", status="Open", decision="—", effective="—"),
    dict(id="19-B", chapter=19, issue="Confirm which inferred edges require mandatory human validation before appearing in any shared view.",
         category="INSTITUTIONAL", impact="Under-scoping risks an unvalidated ARGUS-Proposed or Human-Inferred edge being mistaken for fact in a shared view.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved validation-requirement policy per edge origin.", status="Open", decision="—", effective="—"),
    dict(id="19-C", chapter=19, issue="Confirm sensitive graph traversal rules where a path would cross a protected-identity or Anti-Fraud boundary.",
         category="INSTITUTIONAL", impact="Under-scoping risks a Fusion query indirectly exposing protected/sensitive data via a multi-hop traversal.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA IT Security / Anti-Fraud",
         evidence="Approved sensitive-traversal policy.", status="Open", decision="—", effective="—"),

    dict(id="20-A", chapter=20, issue="Confirm retention period for ARGUS Interactions and Contributions.",
         category="INSTITUTIONAL", impact="Feeds Ch.31 retention scheduling; unresolved, ARGUS interaction data has no governed disposition timeline.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function / AI Governance",
         evidence="Approved retention period for ARGUS Interaction/Contribution.", status="Open", decision="—", effective="—"),
    dict(id="20-B", chapter=20, issue="Confirm which model/tool metadata NCA requires retained for audit versus what can be summarised.",
         category="INSTITUTIONAL", impact="Under-retention could remove metadata later needed to explain an ARGUS-assisted Finding; over-retention adds unnecessary storage/privacy exposure.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA Audit & Compliance",
         evidence="Approved model/tool metadata retention policy.", status="Open", decision="—", effective="—"),
    dict(id="20-C", chapter=20, issue="Confirm treatment of private versus shared ARGUS interactions under applicable records/privacy policy.",
         category="LEGAL", impact="Unresolved, private ARGUS interactions could be treated inconsistently under records-retention obligations.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Data Protection",
         evidence="NCA records/privacy policy applied to private vs shared ARGUS interactions.", status="Open", decision="—", effective="—"),
    dict(id="20-D", chapter=20, issue="(v0.4) Confirm retention period for Agent Definitions, Agent Runs and VPF Validation Artifacts (Ch.3 §3.9).",
         category="INSTITUTIONAL", impact="Feeds Ch.31 retention scheduling; unresolved, the new Agent/VPF entity family has no governed disposition timeline.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function / AI Governance",
         evidence="Approved retention period for Agent Definition/Run/VPF Validation Artifact.", status="Open", decision="—", effective="—"),
    dict(id="20-E", chapter=20, issue="(v0.4) Confirm canonical stewardship for VPF Profiles distinct from the entity-family ownership already raised in Ch.3 §3.9 (3-C).",
         category="INSTITUTIONAL", impact="Unclear stewardship risks VPF Profiles being changed without a defined governance authority.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function / AI Governance",
         evidence="Approved VPF Profile stewardship assignment.", status="Open", decision="—", effective="—"),
    dict(id="20-F", chapter=20, issue="(v0.4) Confirm retention period for Promotion Candidates and ownership for Engineering Change Candidates (Ch.3 §3.9).",
         category="INSTITUTIONAL", impact="Unclear retention/ownership risks these records accumulating without a clear disposition or accountable owner.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved retention period and ownership assignment.", status="Open", decision="—", effective="—"),

    dict(id="21-A", chapter=21, issue="Confirm Room types and membership rules (who may create a Room, invite participants).",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.26 role scoping for Room creation/invitation.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function / Collaboration Governance",
         evidence="Approved Room-type and membership policy.", status="Open", decision="—", effective="—"),
    dict(id="21-B", chapter=21, issue="Confirm default Participation Mode per Room type (ordinary vs Anti-Fraud/regulatory rooms).",
         category="INSTITUTIONAL", impact="An unconfirmed default risks an overly proactive ARGUS in a sensitive room, or an overly silent one in an ordinary room.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function / Anti-Fraud",
         evidence="Approved default Participation Mode per Room type.", status="Open", decision="—", effective="—"),
    dict(id="21-C", chapter=21, issue="Confirm how Consensus, Dissent and private-to-room sharing should work in edge cases (e.g. a participant leaving mid-discussion).",
         category="INSTITUTIONAL", impact="Under-specified edge-case handling risks inconsistent behaviour once real rooms are used at scale.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved edge-case handling rules.", status="Open", decision="—", effective="—"),

    dict(id="22-A", chapter=22, issue="Confirm memory retention period by Memory Class.",
         category="INSTITUTIONAL", impact="Feeds Ch.31 retention scheduling for Private/Shared/Institutional Memory.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function / Knowledge Management",
         evidence="Approved retention period per Memory Class.", status="Open", decision="—", effective="—"),
    dict(id="22-B", chapter=22, issue="Confirm Institutional Knowledge owners, reviewers and approvers.",
         category="INSTITUTIONAL", impact="Blocks operationalising the promotion workflow in §22.4.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved owner/reviewer/approver assignment.", status="Open", decision="—", effective="—"),
    dict(id="22-C", chapter=22, issue="Confirm what may become organisation-wide Institutional Knowledge versus remaining room- or user-scoped.",
         category="INSTITUTIONAL", impact="Under-scoping risks either over-sharing sensitive room-derived knowledge or under-using genuinely valuable institutional patterns.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved scope-promotion policy.", status="Open", decision="—", effective="—"),

    dict(id="23-A", chapter=23, issue="Confirm which workflows are high-consequence and require mandatory Approval before Automation/RPA Run execution.",
         category="INSTITUTIONAL", impact="Under-scoping risks a high-consequence automated action executing without the separation-of-duties Approval it needs.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Automation/RPA Governance",
         evidence="Approved high-consequence workflow list.", status="Open", decision="—", effective="—"),
    dict(id="23-B", chapter=23, issue="Confirm approval matrices per workflow category.",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.26 role scoping for workflow Approval.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Automation/RPA Governance",
         evidence="Approved approval matrix per workflow category.", status="Open", decision="—", effective="—"),
    dict(id="23-C", chapter=23, issue="Confirm which external systems require RPA versus API integration today.",
         category="SOURCE_DISCOVERY", impact="Blocks provider-adapter build sequencing in NCIE-017/NCIE-004.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA IT / Automation Governance",
         evidence="Confirmed integration-mode inventory per external system.", status="Open", decision="—", effective="—"),

    dict(id="24-A", chapter=24, issue="The current supplied values (surcharge USD 0.19; Ghana Card limit 10; Passport limit 3) are proposed as the initial Rule Version values at go-live.",
         category="PROPOSED", impact="If overridden, only the Rule Version values change — no schema change needed, by design (this is the same item as 14-A, restated at its Ch.24 owning point).",
         blocking="Non-blocking (default stands until overridden)", proposed="Surcharge USD 0.19; Ghana Card 10; Passport 3, as initial Rule Version values.",
         owner="NCA Revenue Assurance / Registration Policy", evidence="NCA confirmation or override.", status="Open — proposed default standing", decision="—", effective="—"),
    dict(id="24-B", chapter=24, issue="Confirm which values users may modify at what administrative level, and the approval/effective-date process for each rule key.",
         category="INSTITUTIONAL", impact="Blocks finalising the Rule administration surface's permission model.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Rules & Rates Governance",
         evidence="Approved per-rule-key administration and approval process.", status="Open", decision="—", effective="—"),
    dict(id="24-C", chapter=24, issue="Confirm rule-conflict and rollback behaviour expectations beyond the block-on-conflict default in §24.6.",
         category="INSTITUTIONAL", impact="Under-specified expectations risk operational confusion the first time a real Rule Conflict State occurs.",
         blocking="Non-blocking (default stands until overridden)", proposed=None, owner="NCA Rules & Rates Governance",
         evidence="Approved conflict/rollback handling expectations.", status="Open", decision="—", effective="—"),

    dict(id="25-A", chapter=25, issue="Confirm how much lineage is mandatory by object class.",
         category="INSTITUTIONAL", impact="Under-scoping full lineage for Revenue/Findings would weaken exactly the defensibility this chapter exists to provide.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved lineage-depth requirement per object class.", status="Open", decision="—", effective="—"),
    dict(id="25-B", chapter=25, issue="Confirm archival period for Snapshots.",
         category="INSTITUTIONAL", impact="Feeds Ch.31/Ch.35 archival tiering; unresolved, Snapshot storage growth is unbounded.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved Snapshot archival period.", status="Open", decision="—", effective="—"),
    dict(id="25-C", chapter=25, issue="Confirm which Decisions require formal Decision-Time Context reconstruction versus a lighter-weight audit trail.",
         category="INSTITUTIONAL", impact="Under-scoping risks a Decision later needing full reconstruction that was never captured.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Regulatory Intelligence",
         evidence="Approved Decision-Time-reconstruction scoping.", status="Open", decision="—", effective="—"),

    dict(id="26-A", chapter=26, issue="Confirm enterprise identity provider (SSO) and existing role model at NCA.",
         category="SOURCE_DISCOVERY", impact="Blocks integrating Ch.26's Identity Service with NCA's real authentication infrastructure.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA IT Security / Identity",
         evidence="Confirmed identity provider and existing role model.", status="Open", decision="—", effective="—"),
    dict(id="26-B", chapter=26, issue="Confirm privileged/step-up authentication requirements per role.",
         category="INSTITUTIONAL", impact="Under-scoping risks insufficient authentication strength for Investigator/Administrator-class actions.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA IT Security",
         evidence="Approved step-up authentication policy per role.", status="Open", decision="—", effective="—"),
    dict(id="26-C", chapter=26, issue="Confirm delegation and emergency-access (break-glass) policies.",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.36's break-glass control design.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA IT Security",
         evidence="Approved delegation/break-glass policy.", status="Open", decision="—", effective="—"),

    dict(id="27-A", chapter=27, issue="Confirm audit retention period against applicable records/regulatory requirements.",
         category="LEGAL", impact="Under-retention could remove audit evidence needed for a future regulatory or legal inquiry.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Audit & Compliance",
         evidence="NCA records/regulatory retention requirement for audit data.", status="Open", decision="—", effective="—"),
    dict(id="27-B", chapter=27, issue="Confirm which read operations beyond §27.4's list require audit.",
         category="INSTITUTIONAL", impact="Under-scoping risks a consequential read going unaudited.",
         blocking="Non-blocking (can proceed provisionally, §27.4 already covers the highest-risk cases)", proposed=None, owner="NCA Audit & Compliance",
         evidence="Approved extended audited-read list.", status="Open", decision="—", effective="—"),
    dict(id="27-C", chapter=27, issue="Confirm fail-closed requirements for each high-consequence action category.",
         category="INSTITUTIONAL", impact="Under-scoping risks a high-consequence action proceeding without audit during an Audit Service outage.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Audit & Compliance",
         evidence="Approved fail-closed requirement per action category.", status="Open", decision="—", effective="—"),

    dict(id="28-A", chapter=28, issue="Confirm integration/event platform standards already in use, if any, at NCA.",
         category="SOURCE_DISCOVERY", impact="A conflicting existing standard would require adapting Ch.28's Event Bus contract.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA IT / Integration",
         evidence="Confirmed existing integration/event platform, if any.", status="Open", decision="—", effective="—"),
    dict(id="28-B", chapter=28, issue="Confirm external notification channels (email, SMS, dashboard) required at launch.",
         category="INSTITUTIONAL", impact="Under-scoping risks a launch notification requirement going unmet.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA Operations",
         evidence="Approved launch notification-channel list.", status="Open", decision="—", effective="—"),
    dict(id="28-C", chapter=28, issue="Confirm which event payloads may leave NCIE's boundary and under what data-handling policy.",
         category="LEGAL", impact="Under-scoping risks a sensitive payload leaving NCIE's boundary without proper data-handling controls.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / IT Security",
         evidence="Approved external-payload data-handling policy.", status="Open", decision="—", effective="—"),

    dict(id="29-A", chapter=29, issue="Confirm domain-specific freshness thresholds per source.",
         category="INSTITUTIONAL", impact="Feeds Ch.24 Rule Version values for Freshness State; unresolved, staleness detection uses only placeholder thresholds.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function (per-domain)",
         evidence="Approved per-domain freshness thresholds.", status="Open", decision="—", effective="—"),
    dict(id="29-B", chapter=29, issue="Confirm data-quality ownership (who is accountable for a given source's Remediation Tasks).",
         category="INSTITUTIONAL", impact="Unclear ownership risks Remediation Tasks going unassigned in practice.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved data-quality ownership assignment.", status="Open", decision="—", effective="—"),
    dict(id="29-C", chapter=29, issue="Confirm which quality failures block downstream processing entirely versus merely flag it.",
         category="INSTITUTIONAL", impact="Under-scoping risks either blocking too aggressively (losing usable partial data) or too permissively (letting bad data through).",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved blocking-vs-flagging policy per quality-issue type.", status="Open", decision="—", effective="—"),

    dict(id="30-A", chapter=30, issue="Approve the mandatory dictionary columns in §30.3 as binding for Chapter 39 and any future NCIE-004 implementation-level dictionary.",
         category="INSTITUTIONAL", impact="Without approval, NCIE-004 could adopt a different, incompatible dictionary structure.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function",
         evidence="Recorded approval of §30.3's column set.", status="Open", decision="—", effective="—"),
    dict(id="30-B", chapter=30, issue="Confirm naming/abbreviation conventions for Technical Name beyond Chapter 2's baseline rules.",
         category="INSTITUTIONAL", impact="Under-specified conventions risk inconsistent technical naming once many contributors populate the dictionary.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved extended naming/abbreviation convention.", status="Open", decision="—", effective="—"),
    dict(id="30-C", chapter=30, issue="Confirm ownership/stewardship metadata conventions (how an Owner is identified and kept current).",
         category="INSTITUTIONAL", impact="Under-specified stewardship risks dictionary entries with stale or missing owners over time.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved stewardship-metadata convention.", status="Open", decision="—", effective="—"),

    dict(id="31-A", chapter=31, issue="Confirm classification taxonomy against applicable Ghanaian data-protection law and NCA policy.",
         category="LEGAL", impact="An unconfirmed taxonomy risks NCIE-003's protected/sensitive tiers not actually matching legal obligations.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Data Protection",
         evidence="NCA legal review of the classification taxonomy.", status="Open", decision="—", effective="—"),
    dict(id="31-B", chapter=31, issue="Confirm retention schedules and legal-hold procedures.",
         category="LEGAL", impact="Consolidates the many chapter-specific retention items above (5-C, 9-C, 17-C, 20-A, 22-A, 27-A) into one governed schedule.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Compliance",
         evidence="Approved master retention schedule and legal-hold procedure.", status="Open", decision="—", effective="—"),
    dict(id="31-C", chapter=31, issue="Confirm privacy obligations specific to Ghana Card/Passport-derived data.",
         category="LEGAL", impact="Directly affects Ch.14's field-level protection scope (14-C) and Ch.36's masking design.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / Data Protection",
         evidence="NCA legal opinion on Ghana Card/Passport data handling.", status="Open", decision="—", effective="—"),

    dict(id="32-A", chapter=32, issue="Confirm approved enterprise platforms/technologies for each store type in §32.3.",
         category="INSTITUTIONAL", impact="Blocks finalising the Logical-to-Physical Map and, transitively, NCIE-014.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA IT Infrastructure",
         evidence="Approved platform selection per store type.", status="Open", decision="—", effective="—"),
    dict(id="32-B", chapter=32, issue="Confirm hosting constraints (on-prem/sovereign cloud).",
         category="INSTITUTIONAL", impact="Directly affects Ch.36's sovereignty control design and platform selection in 32-A.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA IT Infrastructure / Legal",
         evidence="Approved hosting-model decision.", status="Open", decision="—", effective="—"),
    dict(id="32-C", chapter=32, issue="Confirm which stores may contain restricted/sensitive data given each candidate technology's own security posture.",
         category="LEGAL", impact="Selecting a store without adequate security posture for sensitive data would create a compliance gap.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / IT Security",
         evidence="Security assessment of candidate store technologies.", status="Open", decision="—", effective="—"),

    dict(id="33-A", chapter=33, issue="Confirm preferred API/event standards already in use at NCA.",
         category="SOURCE_DISCOVERY", impact="A conflicting existing standard would require adapting Ch.33's contract format.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA IT / Integration",
         evidence="Confirmed existing API/event standards, if any.", status="Open", decision="—", effective="—"),
    dict(id="33-B", chapter=33, issue="Confirm versioning/deprecation policy timelines.",
         category="INSTITUTIONAL", impact="Under-specified timelines risk consumers breaking when a schema is deprecated without adequate notice.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved deprecation-timeline policy.", status="Open", decision="—", effective="—"),
    dict(id="33-C", chapter=33, issue="Confirm external operator contract constraints (e.g. fixed formats operators already use for regulatory submissions).",
         category="SOURCE_DISCOVERY", impact="An unconfirmed operator format constraint could conflict with Ch.33's schema evolution rules.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA IT / Integration",
         evidence="Confirmed operator submission format constraints.", status="Open", decision="—", effective="—"),

    dict(id="34-A", chapter=34, issue="Inventory legacy systems that require migration and their current data owners.",
         category="SOURCE_DISCOVERY", impact="Blocks any migration planning at all — the Legacy Source entity remains unpopulated without it.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCA IT / Legacy Systems",
         evidence="Completed legacy-system inventory.", status="Open", decision="—", effective="—"),
    dict(id="34-B", chapter=34, issue="Confirm migration priorities and required historical depth.",
         category="INSTITUTIONAL", impact="Under-scoping risks migrating too little history to support Ch.5/Ch.25's reconstruction requirements.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved migration priority and depth plan.", status="Open", decision="—", effective="—"),
    dict(id="34-C", chapter=34, issue="Confirm acceptable manual-reconciliation procedures for Exceptions.",
         category="INSTITUTIONAL", impact="Under-specified procedures risk migration Exceptions accumulating without a clear resolution path.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved manual-reconciliation procedure.", status="Open", decision="—", effective="—"),

    dict(id="35-A", chapter=35, issue="Confirm expected data volumes and retention horizons per entity family.",
         category="SOURCE_DISCOVERY", impact="Blocks sizing Ch.35's Partition Strategy and Capacity Metadata realistically.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA IT Infrastructure",
         evidence="Confirmed volume/retention estimates per entity family.", status="Open", decision="—", effective="—"),
    dict(id="35-B", chapter=35, issue="Confirm performance targets (translate NCIE-002 Ch.30's proposed baseline into per-entity-family SLOs).",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.35's Performance SLO entity with real targets.",
         blocking="Non-blocking (can proceed provisionally with NCIE-002's proposed baseline)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved per-entity-family performance SLOs.", status="Open", decision="—", effective="—"),
    dict(id="35-C", chapter=35, issue="Confirm archive-retrieval SLA expectations for Cold-tier data.",
         category="INSTITUTIONAL", impact="Under-specified SLA risks operational disappointment when Cold-tier data is later requested urgently.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA IT Infrastructure",
         evidence="Approved archive-retrieval SLA.", status="Open", decision="—", effective="—"),

    dict(id="36-A", chapter=36, issue="Confirm sovereignty/residency requirements with NCA legal/IT security leadership.",
         category="LEGAL", impact="This is the single most consequential open item for hosting-model and technology-selection decisions across Ch.32/Ch.35.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Legal / IT Security",
         evidence="NCA sovereignty/residency policy determination.", status="Open", decision="—", effective="—"),
    dict(id="36-B", chapter=36, issue="Confirm encryption/key-management standards and rotation policy.",
         category="INSTITUTIONAL", impact="Blocks finalising Ch.36's Key Reference and rotation design.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA IT Security",
         evidence="Approved encryption/key-management standard.", status="Open", decision="—", effective="—"),
    dict(id="36-C", chapter=36, issue="Confirm which data classes may use external/cloud processing, if any.",
         category="LEGAL", impact="Directly gates whether NCIE-002 Ch.24's external-model policy can ever apply to sensitive-tier NCIE-003 data.",
         blocking="Blocking (regulatory/legal defensibility)", proposed=None, owner="NCA Legal / IT Security",
         evidence="Approved external/cloud-processing policy per data class.", status="Open", decision="—", effective="—"),

    dict(id="37-A", chapter=37, issue="Confirm operational owners and escalation paths per pipeline.",
         category="INSTITUTIONAL", impact="Unclear ownership risks Operational Alerts going unactioned in practice.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA Operations",
         evidence="Approved per-pipeline owner/escalation assignment.", status="Open", decision="—", effective="—"),
    dict(id="37-B", chapter=37, issue="Confirm freshness expectations per domain.",
         category="INSTITUTIONAL", impact="Duplicates and reinforces 29-A; both must be resolved together to fully populate Ch.24's freshness Rule Versions.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function (per-domain)",
         evidence="Approved per-domain freshness expectations.", status="Open", decision="—", effective="—"),
    dict(id="37-C", chapter=37, issue="Confirm acceptable reconciliation windows per entity family.",
         category="INSTITUTIONAL", impact="Under-specified windows risk Reconciliation Jobs running too infrequently to catch drift promptly.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCA Operations",
         evidence="Approved reconciliation-window schedule.", status="Open", decision="—", effective="—"),

    dict(id="38-A", chapter=38, issue="Confirm acceptance authorities for NCIE-003 test results.",
         category="INSTITUTIONAL", impact="Without this, no chapter's Acceptance Evidence can be formally signed off.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Executive Sponsor / QA",
         evidence="Recorded acceptance-authority appointment.", status="Open", decision="—", effective="—"),
    dict(id="38-B", chapter=38, issue="Confirm required test environments and data (masked, per NCIE-002 Ch.29 §29.3 convention).",
         category="INSTITUTIONAL", impact="Blocks scheduling the Temporal/Authorization/Lineage test categories mandated by §38.4.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA IT / QA",
         evidence="Provisioned masked test environment.", status="Open", decision="—", effective="—"),
    dict(id="38-C", chapter=38, issue="Confirm which domain users must sign off on which chapters' Acceptance Evidence.",
         category="INSTITUTIONAL", impact="Blocks assigning real reviewers to each domain chapter's Acceptance Evidence.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved sign-off matrix per chapter.", status="Open", decision="—", effective="—"),

    dict(id="39-A", chapter=39, issue="Every attribute marked SOURCE DISCOVERY REQUIRED in Chapter 39 requires actual NCA/operator system inspection before NCIE-004 implementation begins.",
         category="SOURCE_DISCOVERY", impact="This is the single largest blocking dependency for the Final Production Data Dictionary; it aggregates the source-discovery items above (6-A, 7-A, 7-C, 8-A, 9-A, 10-A, 10-B, 11-A, 12-C, 13-A, 15-A, 15-B, 16-A, 23-C, 26-A, 28-A, 33-A, 33-C, 34-A, 35-A).",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function / NCA Source Owners",
         evidence="Completed source-system inspection for every SOURCE DISCOVERY REQUIRED field.", status="Open", decision="—", effective="—"),
    dict(id="39-B", chapter=39, issue="Confirm which additional entities beyond the 23 representative examples (15 original plus 8 added by the v0.4 Agent & VPF amendment) require full worked treatment before NCIE-003 is considered dictionary-complete.",
         category="INSTITUTIONAL", impact="Determines the remaining scope of work before Chapter 39 can be called the Final Production Data Dictionary.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved full-population scope for Chapter 39.", status="Open", decision="—", effective="—"),

    dict(id="40-A", chapter=40, issue="Confirm preferred diagram notation for the eventual formal ERD deliverable.",
         category="INSTITUTIONAL", impact="Affects only presentation of the already-agreed logical relationships, not their substance.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved diagram-notation standard (e.g. Crow's Foot, IE).", status="Open", decision="—", effective="—"),
    dict(id="40-B", chapter=40, issue="Confirm the level of detail appropriate for architectural review versus what NCIE-004/implementation will need.",
         category="INSTITUTIONAL", impact="Under-scoping risks NCIE-004 needing a deeper ERD pass than this chapter currently provides.",
         blocking="Non-blocking (can proceed provisionally)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved required-detail level for NCIE-004 handover.", status="Open", decision="—", effective="—"),
    dict(id="40-C", chapter=40, issue="Validate each domain's relationships with the relevant domain users before physical implementation begins.",
         category="SOURCE_DISCOVERY", impact="Unvalidated relationships risk a physical implementation built on an unconfirmed logical assumption.",
         blocking="Blocking (production field-level completion)", proposed=None, owner="NCIE Architecture Function (per-domain)",
         evidence="Domain-user validation sign-off per ERD.", status="Open", decision="—", effective="—"),

    dict(id="41-A", chapter=41, issue="Confirm traceability granularity required (chapter-level, as here, versus field-level for every dictionary entry).",
         category="INSTITUTIONAL", impact="Chapter-level granularity is sufficient for architectural review; field-level granularity would be needed for exhaustive implementation audit.",
         blocking="Non-blocking (can proceed provisionally at chapter level)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved traceability-granularity requirement.", status="Open", decision="—", effective="—"),
    dict(id="41-B", chapter=41, issue="Authoritative current architecture/authority baseline for this crosswalk.",
         category="RESOLVED", impact="N/A — already settled.", blocking="Non-blocking",
         proposed=None, owner="N/A", evidence="N/A — resolved by front matter §0.1.",
         status="Closed", decision="(v0.4) Approved NCIE-002 System Architecture & Technical Design, Version 0.5 (VPF & Dynamic Agent Synthesis Architectural Consistency Amendment), together with approved NCIE-001 Master PRD v1.3 and approved NCIE-007 AI, Agent & Model Orchestration Specification v1.1 for Agent Factory-related data semantics, is the authoritative baseline for this crosswalk. Supersedes the prior v0.3 resolution citing NCIE-002 v0.4 alone (preserved as history, front matter §0.8).",
         effective="NCIE-003 v0.4 front matter (originally resolved NCIE-003 v0.2 front matter, citing NCIE-002 v0.4)"),
    dict(id="41-C", chapter=41, issue="Approve the process for resolving any future orphan requirement or field, should one be discovered as the dictionary is populated with real source mappings.",
         category="INSTITUTIONAL", impact="Without a defined process, a future orphan discovery could stall rather than route to a clear resolution.",
         blocking="Non-blocking (no orphan currently exists per §41.3)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved orphan-resolution process.", status="Open", decision="—", effective="—"),

    dict(id="43-A", chapter=43, issue="Confirm NCIE-003 approvers and their scope of authority.",
         category="INSTITUTIONAL", impact="Same underlying item as 1-A and 38-A, restated at the final acceptance gate.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCA Executive Sponsor",
         evidence="Recorded approver appointment with defined scope of authority.", status="Open", decision="—", effective="—"),
    dict(id="43-B", chapter=43, issue="Confirm precisely what NCIE-004 will consume from NCIE-003 versus re-derive independently.",
         category="INSTITUTIONAL", impact="Under-specification risks duplicated or conflicting modelling effort between NCIE-003 and NCIE-004.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved NCIE-003-to-NCIE-004 handover scope.", status="Open", decision="—", effective="—"),
    dict(id="43-C", chapter=43, issue="Confirm the baseline-lock and change-control procedure to apply after acceptance.",
         category="INSTITUTIONAL", impact="Without this, post-acceptance changes to NCIE-003 have no defined governance process.",
         blocking="Blocking (acceptance gate)", proposed=None, owner="NCIE Architecture Function",
         evidence="Approved post-acceptance change-control procedure.", status="Open", decision="—", effective="—"),
]

CATEGORY_ORDER = {"LEGAL": 0, "INSTITUTIONAL": 1, "SOURCE_DISCOVERY": 2, "PROPOSED": 3, "RESOLVED": 4}
BLOCKING_ORDER = {"Blocking": 0, "Non-blocking": 1}


def _blocking_rank(value):
    return 0 if value.startswith("Blocking") else 1


def sorted_register():
    return sorted(
        REGISTER,
        key=lambda item: (_blocking_rank(item["blocking"]), CATEGORY_ORDER[item["category"]], item["chapter"]),
    )
